import { PERMISSION_IDS } from '@core/constants/permissions.constants'
import {
  MAIN_FLOW_TUTORIAL_ID,
  type TutorialDefinition,
} from '@core/interfaces/ui/tutorial.interface'
import { buildMainFlowSteps } from './tutorials/main-flow.steps'
import {
  buildPatientTourSteps,
  buildPatientCreateSteps,
  buildPatientEditSteps,
  buildPatientDeleteSteps,
  buildPatientHistorySteps,
  buildPatientFilterSteps,
} from './tutorials/patient.steps'
import {
  buildShiftCreateSteps,
  buildShiftManageSteps,
  buildShiftHistorySteps,
} from './tutorials/shift.steps'
import {
  buildHistoryTourSteps,
  buildHistoryManageSteps,
  buildHistoryLabOrderSteps,
} from './tutorials/clinical.steps'
import { buildLabTourSteps } from './tutorials/laboratory.steps'
import { buildClientCreateSteps } from './tutorials/sales.steps'
import {
  buildCategoryCreateSteps,
  buildSubcategoryCreateSteps,
  buildSupplierCreateSteps,
  buildProductCreateSteps,
} from './tutorials/catalog.steps'
import {
  buildUserCreateSteps,
  buildRoleCreateSteps,
  buildBranchCreateSteps,
} from './tutorials/admin.steps'

export const MAIN_FLOW_TUTORIAL: TutorialDefinition = {
  id: MAIN_FLOW_TUTORIAL_ID,
  titleKey: 'TUTORIALS.MAIN_FLOW.TITLE',
  descriptionKey: 'TUTORIALS.MAIN_FLOW.DESCRIPTION',
  tag: 'MAIN_FLOW',
  icon: 'ti-route',
  order: 0,
  featured: true,
  buildSteps: buildMainFlowSteps,
}

export const TUTORIALS: TutorialDefinition[] = [
  MAIN_FLOW_TUTORIAL,

  {
    id: 'patient-tour',
    titleKey: 'TUTORIALS.PATIENT.TOUR.TITLE',
    descriptionKey: 'TUTORIALS.PATIENT.TOUR.DESCRIPTION',
    tag: 'PATIENTS',
    icon: 'ti-compass',
    order: 0,
    requiredPermissions: [PERMISSION_IDS.PATIENTS],
    buildSteps: buildPatientTourSteps,
  },
  {
    id: 'patient-create',
    titleKey: 'TUTORIALS.PATIENT.CREATE.TITLE',
    descriptionKey: 'TUTORIALS.PATIENT.CREATE.DESCRIPTION',
    tag: 'PATIENTS',
    icon: 'ti-user-plus',
    order: 1,
    requiredPermissions: [PERMISSION_IDS.PATIENTS],
    buildSteps: buildPatientCreateSteps,
  },
  {
    id: 'patient-edit',
    titleKey: 'TUTORIALS.PATIENT.EDIT.TITLE',
    descriptionKey: 'TUTORIALS.PATIENT.EDIT.DESCRIPTION',
    tag: 'PATIENTS',
    icon: 'ti-edit',
    order: 2,
    requiredPermissions: [PERMISSION_IDS.PATIENTS],
    buildSteps: buildPatientEditSteps,
  },
  {
    id: 'patient-delete',
    titleKey: 'TUTORIALS.PATIENT.DELETE.TITLE',
    descriptionKey: 'TUTORIALS.PATIENT.DELETE.DESCRIPTION',
    tag: 'PATIENTS',
    icon: 'ti-trash',
    order: 3,
    requiredPermissions: [PERMISSION_IDS.PATIENTS],
    buildSteps: buildPatientDeleteSteps,
  },
  {
    id: 'patient-history',
    titleKey: 'TUTORIALS.PATIENT.HISTORY.TITLE',
    descriptionKey: 'TUTORIALS.PATIENT.HISTORY.DESCRIPTION',
    tag: 'PATIENTS',
    icon: 'ti-file-text',
    order: 4,
    requiredPermissions: [PERMISSION_IDS.PATIENTS],
    buildSteps: buildPatientHistorySteps,
  },
  {
    id: 'patient-filter',
    titleKey: 'TUTORIALS.PATIENT.FILTER.TITLE',
    descriptionKey: 'TUTORIALS.PATIENT.FILTER.DESCRIPTION',
    tag: 'PATIENTS',
    icon: 'ti-filter',
    order: 5,
    requiredPermissions: [PERMISSION_IDS.PATIENTS],
    buildSteps: buildPatientFilterSteps,
  },

  {
    id: 'shift-create',
    titleKey: 'TUTORIALS.SHIFT.CREATE.TITLE',
    descriptionKey: 'TUTORIALS.SHIFT.CREATE.DESCRIPTION',
    tag: 'SCHEDULING',
    icon: 'ti-calendar-plus',
    order: 1,
    requiredPermissions: [PERMISSION_IDS.SHIFT_MANAGEMENT],
    buildSteps: buildShiftCreateSteps,
  },
  {
    id: 'shift-manage',
    titleKey: 'TUTORIALS.SHIFT.MANAGE.TITLE',
    descriptionKey: 'TUTORIALS.SHIFT.MANAGE.DESCRIPTION',
    tag: 'SCHEDULING',
    icon: 'ti-calendar-cog',
    order: 2,
    requiredPermissions: [PERMISSION_IDS.SHIFT_MANAGEMENT],
    buildSteps: buildShiftManageSteps,
  },
  {
    id: 'shift-history',
    titleKey: 'TUTORIALS.SHIFT.HISTORY.TITLE',
    descriptionKey: 'TUTORIALS.SHIFT.HISTORY.DESCRIPTION',
    tag: 'SCHEDULING',
    icon: 'ti-file-plus',
    order: 3,
    requiredPermissions: [PERMISSION_IDS.SHIFT_MANAGEMENT],
    buildSteps: buildShiftHistorySteps,
  },

  {
    id: 'history-tour',
    titleKey: 'TUTORIALS.CLINICAL.TOUR.TITLE',
    descriptionKey: 'TUTORIALS.CLINICAL.TOUR.DESCRIPTION',
    tag: 'CLINICAL',
    icon: 'ti-compass',
    order: 0,
    requiredPermissions: [PERMISSION_IDS.MEDICAL_HISTORY],
    buildSteps: buildHistoryTourSteps,
  },
  {
    id: 'history-manage',
    titleKey: 'TUTORIALS.CLINICAL.MANAGE.TITLE',
    descriptionKey: 'TUTORIALS.CLINICAL.MANAGE.DESCRIPTION',
    tag: 'CLINICAL',
    icon: 'ti-file-pencil',
    order: 2,
    requiredPermissions: [PERMISSION_IDS.MEDICAL_HISTORY],
    buildSteps: buildHistoryManageSteps,
  },
  {
    id: 'history-lab-order',
    titleKey: 'TUTORIALS.CLINICAL.LAB_ORDER.TITLE',
    descriptionKey: 'TUTORIALS.CLINICAL.LAB_ORDER.DESCRIPTION',
    tag: 'CLINICAL',
    icon: 'ti-flask',
    order: 3,
    requiredPermissions: [PERMISSION_IDS.MEDICAL_HISTORY],
    buildSteps: buildHistoryLabOrderSteps,
  },

  {
    id: 'lab-tour',
    titleKey: 'TUTORIALS.LABORATORY.TOUR.TITLE',
    descriptionKey: 'TUTORIALS.LABORATORY.TOUR.DESCRIPTION',
    tag: 'LABORATORY',
    icon: 'ti-compass',
    order: 0,
    requiredPermissions: [PERMISSION_IDS.LABORATORY_ORDERS],
    buildSteps: buildLabTourSteps,
  },

  {
    id: 'client-create',
    titleKey: 'TUTORIALS.CLIENT.CREATE.TITLE',
    descriptionKey: 'TUTORIALS.CLIENT.CREATE.DESCRIPTION',
    tag: 'SALES',
    icon: 'ti-user-dollar',
    order: 1,
    requiredPermissions: [PERMISSION_IDS.CLIENTS],
    buildSteps: buildClientCreateSteps,
  },

  {
    id: 'category-create',
    titleKey: 'TUTORIALS.CATEGORY.CREATE.TITLE',
    descriptionKey: 'TUTORIALS.CATEGORY.CREATE.DESCRIPTION',
    tag: 'CATALOG',
    icon: 'ti-category-plus',
    order: 1,
    requiredPermissions: [PERMISSION_IDS.CATEGORIES],
    buildSteps: buildCategoryCreateSteps,
  },
  {
    id: 'subcategory-create',
    titleKey: 'TUTORIALS.CATEGORY.SUBCATEGORY.TITLE',
    descriptionKey: 'TUTORIALS.CATEGORY.SUBCATEGORY.DESCRIPTION',
    tag: 'CATALOG',
    icon: 'ti-subtask',
    order: 2,
    requiredPermissions: [PERMISSION_IDS.CATEGORIES],
    buildSteps: buildSubcategoryCreateSteps,
  },
  {
    id: 'supplier-create',
    titleKey: 'TUTORIALS.SUPPLIER.CREATE.TITLE',
    descriptionKey: 'TUTORIALS.SUPPLIER.CREATE.DESCRIPTION',
    tag: 'CATALOG',
    icon: 'ti-building-store',
    order: 3,
    requiredPermissions: [PERMISSION_IDS.SUPPLIERS],
    buildSteps: buildSupplierCreateSteps,
  },
  {
    id: 'product-create',
    titleKey: 'TUTORIALS.PRODUCT.CREATE.TITLE',
    descriptionKey: 'TUTORIALS.PRODUCT.CREATE.DESCRIPTION',
    tag: 'CATALOG',
    icon: 'ti-package',
    order: 4,
    requiredPermissions: [PERMISSION_IDS.INVENTORY],
    buildSteps: buildProductCreateSteps,
  },

  {
    id: 'user-create',
    titleKey: 'TUTORIALS.USER.CREATE.TITLE',
    descriptionKey: 'TUTORIALS.USER.CREATE.DESCRIPTION',
    tag: 'ADMIN',
    icon: 'ti-user-plus',
    order: 1,
    requiredPermissions: [PERMISSION_IDS.USERS],
    buildSteps: buildUserCreateSteps,
  },
  {
    id: 'role-create',
    titleKey: 'TUTORIALS.ROLE.CREATE.TITLE',
    descriptionKey: 'TUTORIALS.ROLE.CREATE.DESCRIPTION',
    tag: 'ADMIN',
    icon: 'ti-user-shield',
    order: 2,
    requiredPermissions: [PERMISSION_IDS.ROLES],
    buildSteps: buildRoleCreateSteps,
  },
  {
    id: 'branch-create',
    titleKey: 'TUTORIALS.BRANCH.CREATE.TITLE',
    descriptionKey: 'TUTORIALS.BRANCH.CREATE.DESCRIPTION',
    tag: 'ADMIN',
    icon: 'ti-building',
    order: 3,
    requiredPermissions: [PERMISSION_IDS.BRANCHES],
    buildSteps: buildBranchCreateSteps,
  },
]
