DO
$$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_user WHERE usename = 'Zofta') THEN
    CREATE USER "Zofta" WITH PASSWORD 'Zgames-Ofta0101@';
  END IF;
END
$$;

DO
$$
BEGIN
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO "Zofta"', current_database());
END
$$;

GRANT USAGE ON SCHEMA public TO "Zofta";

GRANT
SELECT,
INSERT
,
UPDATE,
DELETE ON ALL TABLES IN SCHEMA public TO "Zofta";

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "Zofta";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT
SELECT,
INSERT
,
UPDATE,
DELETE ON TABLES TO "Zofta";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE,
SELECT ON SEQUENCES TO "Zofta";