// Constantes de IDs de permisos (añadir mas despues ya que son las misma para ver)
export const PERMISSION_IDS = {
  // Dashboard
  DASHBOARD: 'b78c4b4d-aa1f-4157-b0f1-6a873219ebed',
  DASHBOARD_VIEW: 'b78c4b4d-aa1f-4157-b0f1-6a873219ebed',

  // Usuarios
  USERS: '0669f8b2-2296-436f-bbd1-650c587225ca',

  // Roles y Permisos
  ROLES: '7061e7e7-cc65-4017-b39c-0cb02ca6b8c6',

  //inventario
  INVENTORY: 'b960b6bd-de11-40c3-9a84-2e9fd44aad9c',

  //historial clínico
  MEDICAL_HISTORY: 'bc60fcd8-791b-4371-8910-6f21b8baa446',
  MEDICAL_HISTORY_CONFIGURATION: '58933118-495e-414e-95ba-1629a7e42de8',

  //gestión de turnos
  SHIFT_MANAGEMENT: '54f13404-f1b1-4313-9351-8e979058bd28',

  //sucursales
  BRANCHES: '66af3090-2664-4faf-8d76-302b6662da5e',

  //compañías no es real thiss cambiar, usé el id de sucursales
  COMPANIES: '66af3090-2664-4faf-8d76-302b6662da5e',

  //selector de sucursales
  BRANCH_SELECTOR: '27b89d1b-68ad-4055-91ed-3475c4495a7a',

  //calendario
  CALENDAR: '3476e77d-5402-49f6-b9c5-29657cc6270f',

  //órdenes de laboratorio
  LABORATORY_ORDERS: '926be685-1920-4ca9-88e1-7ce82e2b51ee',

  //proveedores
  SUPPLIERS: '0ec24ecf-9cde-445c-afc7-dde23f7d7477',

  //categorías
  CATEGORIES: 'c69d4b40-0d45-43a7-abb9-e3195ffb382b',

  //pacientes
  PATIENTS: '1d77ac5d-4342-49b6-8a91-3a120aab48cd',
} as const

// Mapeo de nombres de permisos a IDs para compatibilidad hacia atrás
export const PERMISSION_NAME_TO_ID_MAP: { [key: string]: string } = {
  DASHBOARD_VIEW: PERMISSION_IDS.DASHBOARD_VIEW,
  INVENTORY: PERMISSION_IDS.INVENTORY,
  MEDICAL_HISTORY: PERMISSION_IDS.MEDICAL_HISTORY,
  MEDICAL_HISTORY_CONFIGURATION: PERMISSION_IDS.MEDICAL_HISTORY_CONFIGURATION,
  SHIFT_MANAGEMENT: PERMISSION_IDS.SHIFT_MANAGEMENT,
  BRANCHES: PERMISSION_IDS.BRANCHES,
  CALENDAR: PERMISSION_IDS.CALENDAR,
  BRANCH_SELECTOR: PERMISSION_IDS.BRANCH_SELECTOR,
}

// Mapeo de módulos a IDs de permisos
export const MODULE_NAME_TO_PERMISSION_MAP: { [key: string]: string } = {
  USERS: PERMISSION_IDS.USERS,
  ROLES: PERMISSION_IDS.ROLES,
  PERMISSIONS: PERMISSION_IDS.ROLES,
  DASHBOARD: PERMISSION_IDS.DASHBOARD,
  INVENTORY: PERMISSION_IDS.INVENTORY,
  MEDICAL_HISTORY: PERMISSION_IDS.MEDICAL_HISTORY,
  MEDICAL_HISTORY_CONFIGURATION: PERMISSION_IDS.MEDICAL_HISTORY_CONFIGURATION,
  SHIFT_MANAGEMENT: PERMISSION_IDS.SHIFT_MANAGEMENT,
  BRANCHES: PERMISSION_IDS.BRANCHES,
  CALENDAR: PERMISSION_IDS.CALENDAR,
  LABORATORY_ORDERS: PERMISSION_IDS.LABORATORY_ORDERS,
  SUPPLIERS: PERMISSION_IDS.SUPPLIERS,
  CATEGORIES: PERMISSION_IDS.CATEGORIES,
  COMPANIES: PERMISSION_IDS.COMPANIES,
  PATIENTS: PERMISSION_IDS.PATIENTS,
}

// Alias más legibles para templates
export const PERMISSIONS = {
  dashboard: PERMISSION_IDS.DASHBOARD,
  users: PERMISSION_IDS.USERS,
  roles: PERMISSION_IDS.ROLES,
  inventory: PERMISSION_IDS.INVENTORY,
  medicalHistory: PERMISSION_IDS.MEDICAL_HISTORY,
  shiftManagement: PERMISSION_IDS.SHIFT_MANAGEMENT,
  branches: PERMISSION_IDS.BRANCHES,
  calendar: PERMISSION_IDS.CALENDAR,
  laboratoryOrders: PERMISSION_IDS.LABORATORY_ORDERS,
  suppliers: PERMISSION_IDS.SUPPLIERS,
  categories: PERMISSION_IDS.CATEGORIES,
  companies: PERMISSION_IDS.COMPANIES,
  branchSelector: PERMISSION_IDS.BRANCH_SELECTOR,
  patients: PERMISSION_IDS.PATIENTS,
} as const

export type PermissionId = (typeof PERMISSION_IDS)[keyof typeof PERMISSION_IDS]
